### ISSUE TITLE
Little bug on your website

### ISSUE THREAD

**Issue by danyaPostfactum** [rstacruz/jquery.transit#193]
At the bottom you recommend webkit antialias fix:

``` css
.box {
  -webkit-transition: translate3d(0,0,0);
}
```

That should be `-webkit-transform`
