### ISSUE TITLE
Feature request: more support for Webkit's 3D transforms

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/jquery.transit#2]
http://www.webkit.org/blog/386/3d-transforms/

CSS hooks for:

``` css
    -webkit-transform-origin: x, y, z
    -webkit-perspective: px /* maybe not needed? */
    -webkit-transform-style: { flat | preserves-3d }
    -webkit-backface-visibility: { visible | hidden }
```
