### ISSUE TITLE
support css order change

### ISSUE THREAD

**Issue by RelicOfTesla** [rstacruz/jquery.transit#229]
im css(rotate) at any remote place.
when i will change x,y  on after...
it's bad position todo.

``` CSS
.xx{ transform : translate(50px,0px) rotate(60deg); }
.xx{ transform : rotate(60deg)  translate(50px,0px);  }
```

it's different result with position .
